### PR TITLE
Minor improvements for codebase

### PR DESCRIPTION
**Pull request by leo**
I love this project! 😊

Here are a few adjustments that I thought would make it even sweeter. I also suggest putting JSON into the Travis CI config, as that's the recommended object notation language for JS projects.

To make it 👌, I even suggest disabling the Wiki and the Projects, as they're not needed.

### CODE REVIEW

**Comment by lukeed** [comment]
Hi @leo, thanks! I'm glad you like it 😆 

I removed the Wiki & Projects tabs -- forgot about those.

Do you mind reverting the `License` section on the readme & the `.gitignore` changes? 

Thanks! 🕺

**Comment by leo** [comment]
@lukeed On GitHub, I don't think we're supposed to show the license by ourselves anymore anywhere since they've introduced this (it updates automatically):

screen shot 2017-07-24 at 10 12 14

Regarding the `.gitignore` changes: Why? Are you missing .DS_Store? That should be ignored globally by default, shouldn't it? I also don't understand why you don't want the comments that I've introduced there... 😊

**Comment by lukeed** [comment]
License: Yeah, but is best to include it on the docs IMO. Honestly, how often do you ever look at a `license` file or the GitHub corner? How often do you look at a readme? 😉 

Gitignore: I have `DS_Stores` not hidden by default, so I need them ignored. Also comments are unnecessary IMO since the file is tiny & there's as many comments as there are declarations 😆 

Sorry that they're both nit-picks!

**Comment by leo** [comment]
LOL, then I changed nearly nothing. Anyway: Adjusted it... 😄

**Comment by lukeed** [comment]
Lol, style changes! Appreciate it all the same 🙏

**Pull request merged**
