### PR TITLE
chore: drop support for old nodejs and some little performance improvements

### PR DESCRIPTION
**Pull request by poppinlp**
- Drop support for old nodejs according to the [official schedule](https://nodejs.org/en/about/releases/).
- Some little performance improvements. You may see the result below.
- Update `gitignore` comes from [gitignore repo](https://github.com/github/gitignore)

This benchmark result comes from a temp script. The "origin" means mri 1.1.5. The "mri" means the current branch code.

image

### CODE REVIEW

**Comment by poppinlp** [comment]
Thanks for a pretty nice tool!
Actually, I wanna rewrite more code to make it more readable and modern. But don't know whether you like it. :)

**Comment by lukeed** [comment]
Hi, thank you :)

What version of Node are you running the tests on? Here's what I get with Node v10.13
Screen Shot 2020-04-30 at 8 17 55 AM
Screen Shot 2020-04-30 at 8 14 27 AM

And then to make sure that order (aka, warming) wasn't the cause:

Screen Shot 2020-04-30 at 8 18 08 AM

Which makes sense for the code changes. Your changes are choosing the slower variants of each operation (`for` -> `for-of`; `for-in` -> `Object.keys() + for-of`; `substring` -> `slice`) and you're creating more variable space.

Finally, there's actually no reason to drop Node 4 support. Not only is that a major/breaking change, but we're not _using_ anything from newer runtimes that is (a) necessary for the upgrade or (b) that Node 4.x can't syntactically support. In other words, all that's been added are `const` and `for-of` loops – Node 4.x supports both. And it's not like we're adding `async` usage.

---

> make it more readable and modern

I don't like these kinds of PRs, sorry 🙈 If I'm not writing TS, then library code exists as ES5 for a reason, on top of it being my personal code style to write the way I write.

---

I'd still like to know which version of Node you're testing on, but I don't think I'll be able to accept this PR. I appreciate the time and enthusiasm you've invested! I wish you would have opened a ticket first so we could discuss changes so that your efforts aren't for naught.

Hope you can understand where I'm coming from. Happy to discuss further.

Thanks again~!

**Comment by poppinlp** [comment]
The result came from Node 14. But I haven't tested it on other Node versions. That's my fault.

I've tested the performance on jsperf for `substring` -> `slice` and `charCodeAt` -> `[]` which has better performance especially `charCodeAt` -> `[]`. And the `splice` is slow also. So I made those changes. But I haven't tested the `for-of`.

Actually, there are some changes just for more readable. And as you said, they create more variable space. So, I know your opinion about this right now and I won't do that. :)

Maybe I'll revert most changes and test on more Node versions. If there is still some buff, I'll create another PR.

Thanks.

**Comment by poppinlp** [comment]
By the way, the `toArr` helper right now could return something like `[true]` for option like `boolean: true`. Do you think it's right? Or may return `[]` for non-string value.

**Comment by poppinlp** [comment]
Hi. I just run a test on jsperf for `for-in` and `for-of + Object.keys`. Here's the result:

image

And here's my env: Testing in Chrome 81.0.4044 / Mac OS X 10.15.4.

I guess it's may cause by the upgrade of V8. And V8 may still bump performance for the new syntax. So maybe they more fit the future.

I'll test on more Node versions. But I think I should respect your opinions since you are the owner. :)

**Comment by poppinlp** [comment]
Yep, you are right. It seems the warming effects. I forgot it when I sent this PR. T_T
So I run the tests alternately in my new branch on 3 recent LTS Node versions:

image

**Comment by poppinlp** [comment]
@lukeed Hi. Should I send a new PR for that? Or it's not necessary.

**Pull request closed without merging**
